<--------------DO NOT TOUCH IT!---------------------->


domain: docs.reyo.run

<----------PARTS OF TYPE JS INCLUDED---------->

typejs: Y

newtrojs: N

nyhonojs: N 




<<<<<<<<<<<<<<<<< SUDO BASH >>>>>>>>>>>>>>>>>>>>

sudo apt install docs.reyo.run;

sudo curl script (https://docskters.xyz/script);

sudo curl new - - - - (https://docskters.xyz/new);

<-----------------DATABASE (DOCS)------------------------->

database.manage.docs.reyo();

sudo curl extend database limit = 2tb;